config/routes.rb
Rails.application.routes.draw do

  post '/calculate' => 'cart#calculateDiscount' 
  post '/convert' => 'cart#currencyConvert'
  post '/searchProduct' => 'items#searchProduct'
  get 'orderitem/index'

  get 'orderitem/show'

  get 'orderitem/new'

  get 'orderitem/edit'

  resources :orders do
    resources :orderitems
  end

  devise_for :users do 
    resources :orders
  end

  get '/checkout' => 'cart#createOrder'

  get 'cart/index'

  resources :items
  get 'sitepage/home'
  get '/home' => 'sitepage#home'
  root 'sitepage#home'

  get 'sitepage/aboutus'
  get '/aboutus' => 'sitepage#aboutus'
	
  get '/items' => 'items#index'

  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'

  get '/cart/remove/:id' => 'cart#remove'

end

app/models/item.rb
class Item < ActiveRecord::Base
	
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_filter :ensure_admin, :only => [:new, :create, :edit, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  def searchProduct
    	#@items = Item.all
	search = "%" + params[:search_product] + "%"
	@items = Item.where("items.title LIKE ?", search)
  end	

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url, :category)
    end
#Admin account
def ensure_admin
unless current_user && current_user.admin?
render :text => "Access Error Message", :status => :unauthorized
end
end


end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<!-- DRESSES  Starts -->
		
		<section>
			<div class="">
				<div class="container">
					<div class="heading text-center" style=" padding-top: 0px;" >
						<img class="dividerline" src="/assets/sep.png" alt="">
						<h2><b>DRESSES</b></h2>
						<img class="dividerline" src="/assets/sep.png" alt="">	
					</div>
					<div class="row">
						<% @items.each do |item| %>
						<div class="col-lg-3">
							<blockquote>
								<%= image_tag item.image_url, :style => "width:200px" %>
								<span class="text"><%= item.title %><br>&euro;<%= item.price %>
								<%= link_to 'Show', item %></span>
								<% if user_signed_in? && current_user.admin? %>
								
								<%= link_to 'Edit', edit_item_path(item) %>
								<%= link_to 'Destroy', item, confirm: 'Are you sure?', method: :delete %>
								<% else %>
								<a href="/cart/<%= item.id %>">
									<button type="submit" class="btn btn-warning">Add to Cart</button>
								</a>
								<% end %>
							</blockquote>
						</div>
					<% end %>
					</div>
					<hr>

<% if user_signed_in? && current_user.admin? %>
<b><%= link_to 'Add New Item', new_item_path %></b>
<% end %>

		<!--<%= link_to 'New Item', new_item_path %>-->
				</div>
			</div>
		</section>
		<!-- DRESSES  Ends  -->

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/searchProduct.html.erb
<section>
	<div class="container">
		<div class="heading text-center" style=" padding-top: 0px;" >
			<img class="dividerline" src="/assets/sep.png" alt="">
			<h2><b>SEARCH RESULTS</b></h2>
			<img class="dividerline" src="/assets/sep.png" alt="">	
		</div>
		<% if @items.present? %>
		<% @items.each do |item| %>
		<div class="row">
			<div class="col-lg-4"><%= image_tag item.image_url, :style => "height:120px" %></div>
			<div class="col-lg-8">Title : <%= item.title %><br> Description:<%= item.description %><br>
			<%= link_to 'Show', item %></span></div>
		</div><hr>
		<% end %>
		<% else %>
		<div class="row">
		<div class="col-lg-12"><p> No Result Found !!!! </p></div>
		</div>
		<% end %>
	</div>
</section>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <%= image_tag @item.image_url %>
</p>
<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>
<% if user_signed_in? && current_user.admin? %>
<%= link_to 'Edit', edit_item_path(@item) %> |
<% end %>
<%= link_to 'Back', items_path %>